version: '3.1'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: boilerplate


  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example

volumes:
  mongo:
